### ISSUE TITLE
Adding dplyr Package

### ISSUE THREAD

**Issue by megfletch** [souhfee/issues-lab-3#2]
I believe you will need to add the dyplr package in order for the storms data set to run

https://github.com/souhfee/issues-lab-3/blob/c13caf187fc8cc9f3c17a17db94fb33367b3630e/src/got_issues.Rmd#L7-L9

**Comment by souhfee** [comment]
Thanks for reviewing my code! dplyr is part of the tidyverse package. I'll resolve this.
